# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"show_doc": "00_showdoc.ipynb",
         "doc": "00_showdoc.ipynb",
         "execute_nb": "cli.ipynb",
         "convert_nb": "cli.ipynb",
         "notebook2html": "cli.ipynb",
         "nbdev_build_docs": "cli.ipynb"}

modules = ["showdoc.py",
           "cli.py"]

doc_url = "https://muellerzr.github.io/nbverbose/"

git_url = "https://github.com/muellerzr/nbverbose/tree/master/"

def custom_doc_links(name): return None
